name: quicktranscriptome
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - minimap2
  - samtools
  - subread
  - pandas
  - numpy
  - matplotlib
  - pyyaml
  - requests
  - scipy
  - pydeseq2
  - gseapy
